import HeaderPage from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ContextProvider } from '@/components/glob-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>
        <ContextProvider >
          <HeaderPage />
          <div className=' pt-12'>{children}</div>
        </ContextProvider>
      </body>
    </html>
  )
}
